# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education', models.CharField(max_length=30)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Grade', models.CharField(max_length=1)),
                ('Remark', models.CharField(max_length=30)),
                ('School', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='hrms',
            fields=[
                ('EmployeeNo', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('MaritalStatus', models.CharField(max_length=15)),
                ('GradeEmployee', models.CharField(max_length=10)),
                ('HigestEducation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogser.education')),
            ],
        ),
    ]
